name: "CZ PR TODO Bot"
description: "GitHub Actions to update status check based on Pull Request TODO checklist."
branding:
  icon: "check-square"
  color: "green"
author: "ehoops-cz"
inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    default: ${{ github.token }}
  repository:
    description: "The full name of the repository containing the issue or pull request."
    default: ${{ github.repository }}
runs:
  using: "node16"
  main: "lib/main.js"
